config/routes.rb
Rails.application.routes.draw do
  root 'creatives#index'
  get 'creatives/terms_and_conditions', as: :terms
  get 'creatives/privacy_notice', as: :privacy

  devise_for :users,
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                             passwords: 'users/passwords',
                             registrations: 'users/registrations',
                             sessions: 'users/sessions' }
  resources :users, only: %i[show edit update]
  resources :artists, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :albums, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :reviews, only: %i[create update destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id            :bigint(8)        not null, primary key
#  name          :string(255)
#  image         :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  external_urls :string(255)
#  spotify_id    :string(255)      not null
#

class Artist < ApplicationRecord
  # Associations
  has_many :artists_albums, dependent: :destroy
  has_many :albums, through: :artists_albums

  # Validation
  validates_presence_of :name, :image, :external_urls
  validates :spotify_id, uniqueness: true

  # TODO: 未使用メソッド削除
  class << self
    def pagination(page:)
      page(page).per(Constants::ARTISTS_FOR_ARTISTS_INDEX_PAGE)
    end

    def artists_list(page:)
      order(name: 'ASC').pagination(page: page)
    end

    def search_artists(artist_name:, page:)
      where('name LIKE ?', "%#{artist_name}%").artists_list(page: page)
    end

    def get_top_rating_artists
      self.joins(:albums)
        .order(average_rating: :desc)
        .uniq
        .take(Constants::TOP_RATING_ALBUMS)
    end
  end
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  include ApiClientGeneratable
  include ArtistsHelper

  before_action :generate_spotify_client, only: %i[index show search]
  before_action :generate_youtube_client, only: %i[show]
  before_action :generate_wikipedia_client, only: %i[show]

  def index
    new_releases = @spotify_client.get_new_releases(limit: Constants::NEW_RELEASE_ALBUMS)
    new_release_artists = new_releases.map { |release| release.artists }.flatten # feat.などで1つのアルバムに複数アーティストが存在することがあるので、flattenして二重配列をフラットにする
    artist_ids = new_release_artists.map { |artist| artist.id }
    artists = @spotify_client.get_artists(spotifies_artist_ids: artist_ids)
    top_rating_artists = Artist.get_top_rating_artists

    result = {
      new_release_artists: artists,
      top_rating_artists: top_rating_artists
    }

    render json: result
  end

  def show
    request_params = SpotifyIdRequestParams.new(params)
    request_params.validate!

    service = ShowArtistService.new(
      artist_id: request_params.id,
      spotify_client: @spotify_client,
      youtube_client: @youtube_client,
      wikipedia_client: @wikipedia_client,
      current_user: current_user
    )
    service.run!

    render json: service.result
  end

  def search
    request_params = SearchArtistsRequestParams.new(params)
    request_params.validate!
    artists = @spotify_client.search_artists(artist_name: request_params.artist_name)
    top_rating_artists = Artist.get_top_rating_artists

    result = {
      artists: artists,
      top_rating_artists: top_rating_artists
    }
    render json: result
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.slim
.col-lg-3.col-sm-6.artist
  = link_to artist_path(artist.id), class: "portfolio-box", ontouchstart: "" do
    .image
      = image_tag artist.images.empty? ? Constants::DEFAULT_IMG_URL : artist.images.first["url"], class: "img-responsive img-rounded", alt: artist.name
    .portfolio-box-caption.img-rounded
      .portfolio-box-caption-content
        .project-category.text-faded
          h4
            = artist.name

app/views/artists/_persisted_artist.html.slim
.col-lg-3.col-sm-6.artist
  = link_to artist_path(persisted_artist.spotify_id), class: "portfolio-box", ontouchstart: "" do
    .image
      = image_tag persisted_artist.image.empty? ? Constants::DEFAULT_IMG_URL : persisted_artist.image, class: "img-responsive img-rounded", alt: persisted_artist.name
    .portfolio-box-caption.img-rounded
      .portfolio-box-caption-content
        .project-category.text-faded
          h4
            = persisted_artist.name

app/views/artists/_search.html.slim
= form_with(url: search_artists_path, method: :get, local: true) do |f|
  .form-group.has-search
    span.fa.fa-search.form-control-button
    = f.text_field :artist_name, class: "form-control", placeholder: "Search artists"

app/views/artists/index.html.slim
- provide(:page_title, 'Artists')
.row[style="margin-top:60px;"]
  .search.col-md-6.col-md-offset-3[style="margin-top:40px;"]
    = render partial: 'search'
hr
.row
  #albums-list
    - if @artists.present?
      .panel.panel-default
        .panel-body.text-center
          h4 Results of #{params[:artist_name]}
          = render partial: 'artist', collection: @artists
.row
  .panel.panel-default
    .panel-body.text-center
      h4
        | Top Rating Artists
      = render partial: 'persisted_artist', collection: @top_rating_artists

app/views/artists/show.html.slim
- provide(:page_title, @artist.name)
.row[style="margin-top:65px;"]
  .col-md-4
    .panel.panel-default
      .panel-body
        = image_tag @artist.images.empty? ? Constants::DEFAULT_IMG_URL : @artist.images.first["url"], class: "img-responsive img-rounded text-center"
        h3
          = @artist.name
        p
          / ボタンじゃなくてiconにする
          = link_to icon('fab', 'spotify', 'Go to Spotify'), @artist.external_urls["spotify"], class: 'btn btn-success btn-block', target: '_blank'
        p
          // channelIDで飛んであげるようにする
          / = link_to icon('fab', 'youtube', 'Go to YouTube'), "https://www.youtube.com/channel/#{@channel_id}", class: 'btn btn-danger btn-block', target: '_blank'
        - @artist.genres.each do |genre|
          span.badge[style='margin-right:5px;']
            = genre.capitalize
        - @article.present?
          p[style='margin-top:10px;']
            span[style='word-wrap:break-word;']
              = @article.truncate(500)
              = link_to ' More on Wikipedia', @wiki_url, target: '_blank'

  / TODO: carousel表示にして縦長になりすぎないように
  .col-md-8[style="margin-bottom:20px;"]
    - if @albums.blank?
      h3[style="border-bottom:solid 1px #eee;"]
        | There is no albums...
    - else
      .panel.panel-default
        .panel-body
          .row
            - if @youtube_urls.present?
              h4
                | YouTube
              - @youtube_urls.each do |youtube_url|
                div.col-md-6
                  div.iframe-wrap
                    iframe src="#{youtube_url}" loading="lazy" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture; fullscreen"
          .row
            - if @albums.present?
              h4
                | Albums
              = render partial: 'albums/album', collection: @albums
          .row
            - if @singles.present?
              h4
                | Singles
              = render partial: 'albums/album', collection: @singles
          .row
            - if @compilations.present?
              h4
                | Compilations
              = render partial: 'albums/album', collection: @compilations
hr
.row
  .col-md-12
    .panel.panel-default
      .panel-body.text-center
        h4
          | Related Artists
        = render partial: 'artist', collection: @related_artists
hr
.row
  .col-md-12
    .panel.panel-default
      .panel-body.text-center
        h4
          | Top Rating Artists
        = render partial: 'persisted_artist', collection: @top_rating_artists