config/routes.rb
Rails.application.routes.draw do
  root 'creatives#index'
  get 'creatives/terms_and_conditions', as: :terms
  get 'creatives/privacy_notice', as: :privacy

  devise_for :users,
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                             passwords: 'users/passwords',
                             registrations: 'users/registrations',
                             sessions: 'users/sessions' }
  resources :users, only: %i[show edit update]
  resources :artists, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :albums, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :reviews, only: %i[create update destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  name                   :string(255)      default(""), not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(255)
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string(255)
#  uid                    :string(255)
#  avatar                 :string(255)
#

class User < ApplicationRecord
  # image uploader
  mount_uploader :avatar, AvatarUploader

  # association
  has_many :reviews, dependent: :destroy

  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :confirmable, :lockable,
         :omniauthable, omniauth_providers: %i[facebook]

  # Validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validate :avatar_size

  # TODO: 未使用メソッド削除
  class << self
    # Omniauth
    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first do |user|
        user.name = auth.info.name
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.remote_avatar_url = auth.info.image
      end
    end

    def new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"]
          user.name = data["extra"]["raw_info"]["name"] if user.name.blank?
          user.email = data["extra"]["raw_info"]["email"] if user.email.blank?
          user.password = Devise.friendly_token[0, 20]
          user.provider = data["provider"] if user.provider.blank?
          user.uid = data["uid"] if user.uid.blank?
          user.remote_avatar_url = data["info"]["image"] if user.avatar.blank?
        end
      end
    end
  end

  def user_reviewed_albums
    self.reviews.map { |review| review.album }.uniq
  end

  private

  def avatar_size
    if avatar.size > 5.megabytes
      errors.add(:avatar, "should be less than 5MB")
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  invisible_captcha only: %i[create], honeypot: :subtitle

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :user_signed_in?

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.nil?
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    else
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    end
  end

  # GET|POST /users/auth/facebook/callback
  def failure
    redirect_to new_user_registration_url
  end

  protected

    def after_sign_in_path_for(resource)
      user_path(resource)
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  invisible_captcha only: %i[create update], honeypot: :subtitle

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  def after_resetting_password_path_for(resource)
    user_path(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  include UserAccessable

  invisible_captcha only: %i[create update], honeypot: :subtitle

  before_action :configure_sign_up_params, only: %i[create]
  before_action :configure_account_update_params, only: %i[update]
  before_action only: %i[edit] do
    set_user(user_id: params[:format])
  end
  before_action :prohibit_unspecified_users_access, only: %i[edit update]
  before_action :prohibit_sns_accout_users_access, only: %i[edit update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    added_attrs = %i[
      name
      avatar
      avatar_cache
      remote_avatar
    ]
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_session_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end

  # The path used after update an account
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  invisible_captcha only: %i[create], honeypot: :subtitle

  before_action :user_signed_in?, only: %i[new create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include UserAccessable
  include ApiClientGeneratable
  include UsersHelper

  before_action :authenticate_user!, except: %i[show] # NOTE: 各ユーザの詳細ページは誰でも見れるように
  before_action :generate_spotify_client, only: %i[show]

  def show
    request_params = UserIdRequestParams.new(params)
    request_params.validate!
    service = ShowUserService.new(request_params: request_params, client: @spotify_client, page: params[:page])
    service.run!
    set_instance_variables(service.result)
    render :show
  end

  def edit
    request_params = UserIdRequestParams.new(params)
    request_params.validate!
    @user = User.find(request_params.id)
    prohibit_unspecified_users_access
    render :edit
  end

  def update
    @user = User.find(current_user.id)
    prohibit_unspecified_users_access # NOTE: editと異なりすぐに処理を停止できるためパラメータ検証より先にアクセスコントロールしている
    request_params = UpdateUserRequestParams.new(params)
    request_params.validate!
    @user.update!(request_params.attributes)
    redirect_to @user, notice: 'Your profile was successfully updated.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user:)
    current_user == user
  end

  def set_instance_variables(service_result)
    @user = service_result.user
    @reviews = service_result.reviews
    @user_reviewed_albums = service_result.user_reviewed_albums
    @top_rating_albums = service_result.top_rating_albums
    @new_releases = service_result.new_releases
  end
end

app/views/users/_instruction.html.slim
- if current_user?(user: user)
  .panel.panel-default
    .panel-body.text-center
      h4
        | New releases waiting for your review.
      .highest-rated
        = link_to 'Search Albums', albums_path, class: 'btn btn-primary'
      .row
        = render partial: 'albums/album', collection: new_releases
  .panel.panel-default
    .panel-body.text-center
      h4
        | Top raiting albums
      .highest-rated
        = link_to 'Search Albums', albums_path, class: 'btn btn-primary'
      .row
        = render partial: 'albums/persisted_album', collection: top_rating_albums
- else
  .row
    .col-md-6
      h4
        | There is no review...

app/views/users/_promote_signin.html.slim
.row.text-center
  h5 Please login or signin before review this album &#x1f64f;
  = link_to 'Login', new_user_session_path, class: 'btn btn-success', style: 'margin-right:10px;'
  = link_to 'Signin', new_user_registration_path, class: 'btn btn-primary'

app/views/users/edit.html.slim
- provide(:page_title, 'Edit Account')
.row[style="margin-top:80px;"]
  .col-md-6.col-md-offset-3[style="margin-bottom:20px;"]
    .form-group
      h2[style="margin-bottom:20px;"]
        | Edit your account
      = form_with(model: @user, local: true, url: user_path(@user)) do |f|
        - if @user.errors.any?
          #error_explanation
            h2
              = pluralize(@user.errors.count, "error")
              |  prohibited this user from being saved:
            ul
              - @user.errors.full_messages.each do |message|
                li
                  = message
        .field.text-center[style="margin-bottom:20px;"]
          img#avatar_img_prev.hidden.img-circle[src="#" style="width:150px; height:150px; cursor:pointer;" onclick="$('#user_avatar').click()"]
          = image_tag @user.avatar.file.nil? ? 'default.jpg' : @user.avatar.url, class: 'img-circle avatar_present_img', style: 'cursor:pointer;', onClick:"$('#user_avatar').click()"
        .field.text-center[style="margin-bottom:20px;"]
          span.upload
            label[for="user_avatar" style="color:blue; cursor:pointer;"]
              | Change your avatar
            = f.file_field :avatar, id: :user_avatar, class: 'image-upload', style: 'display:none;', accept: 'image/jpeg,image/jpg,image/png'
            = f.hidden_field :avatar_cache
        .field[style="margin-bottom:20px;"]
          = f.label :name
          = f.text_field :name, placeholder: "Enter your name", class: "form-control"
        .field[style="margin-bottom:20px;"]
          = f.label :email
          = f.email_field :email, placeholder: "Enter email", class: "form-control"
        .actions
          = f.submit "Update", class: "btn btn-success", style: "margin-right:10px;"
          = link_to "Edit password", edit_user_registration_path(@user), class: 'btn btn-warning' if current_user.provider.nil?
    hr
    .back-to-show[style="margin-bottom:20px;"]
      = link_to "Back", user_path(@user), class: "btn btn-default btn-block"
    .cancel-account
      = button_to "Cancel my account", user_registration_path(@user), data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block", method: :delete

app/views/users/show.html.slim
- provide(:page_title, "#{@user.name}")
.row[style="margin-top:80px;"]
  .col-md-4[style="margin-bottom:40px;"]
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            = image_tag @user.avatar.file.nil? ? 'default.jpg' : @user.avatar.url, class: 'img-circle', alt: 'users avatar'
            .username[style="margin:20px 0;"]
              span[style="margin-right:20px;"]
                b
                  = @user.name
              = link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-info' if current_user?(user: @user)
            table
              tr
                td
                  i.fas.fa-comments
                td.text-muted
                  = @reviews.size
                  |  reviews
              tr
                td
                  i.fas.fa-calendar
                td.text-muted
                  = @user.created_at.strftime('%Y %-b %-d')
                  |  joined
        .row.reviewed-albums
          - @user_reviewed_albums.each do |album|
            .col-xs-3
              = link_to image_tag(album.image, class: 'img-responsive img-rounded', style: 'padding:0 -10px;'), album_path(album.spotify_id)
  .col-md-8
    - if @reviews.any?
      .panel.panel-default
        .panel-body
          h4[style="margin:20px;"]
            | Reviewed albums
          - @user_reviewed_albums.each do |album|
            .row[style="margin-bottom:20px; padding-bottom:20px; border-bottom:solid 1px #eee;"]
              .col-md-3[style="margin-bottom:20px;"]
                = link_to image_tag(album.image, class: "img-responsive img-rounded", style: 'margin-right:20px;'), album_path(album.spotify_id)
              .col-md-9
                / このアルバムのレビューだけ表示
                = render partial: 'reviews/review', collection: @reviews.select { |review| review.album == album }
    - else
      = render partial: 'instruction', locals: { user: @user, new_releases: @new_releases, top_rating_albums: @top_rating_albums }