config/routes.rb
Rails.application.routes.draw do
  root 'creatives#index'
  get 'creatives/terms_and_conditions', as: :terms
  get 'creatives/privacy_notice', as: :privacy

  devise_for :users,
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                             passwords: 'users/passwords',
                             registrations: 'users/registrations',
                             sessions: 'users/sessions' }
  resources :users, only: %i[show edit update]
  resources :artists, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :albums, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :reviews, only: %i[create update destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :bigint(8)        not null, primary key
#  name           :string(255)
#  release_date   :string(255)
#  external_urls  :string(255)
#  image          :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  reviews_count  :integer          default(0), not null
#  average_rating :float(24)        default(0.0), not null
#  spotify_id     :string(255)      not null
#

class Album < ApplicationRecord
  # Associations
  has_many :artists_albums, dependent: :destroy
  has_many :artists, through: :artists_albums
  has_many :songs, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Validations
  validates_presence_of :name, :release_date, :external_urls, :image
  validates :spotify_id, uniqueness: true

  # TODO: 未使用メソッド削除
  class << self
    def pagination(page:)
      page(page).per(Constants::ARTISTS_FOR_ARTISTS_INDEX_PAGE)
    end

    def top_ratings(limit:)
      order(average_rating: :desc).limit(limit)
    end
  end

  def update_average_rating
    update_attributes(average_rating: (self.reviews.blank? ? 0.0 : self.reviews.average(:rating).round(2)))
  end
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  include UserAccessable
  include ApiClientGeneratable
  include AlbumsHelper

  before_action :generate_spotify_client, only: %i[index show search]

  def index
    @new_releases = @spotify_client.get_new_releases(limit: Constants::NEW_RELEASE_ALBUMS)
    @top_rating_albums = Album.preload(:artists)
                              .top_ratings(limit: Constants::TOP_RATING_ALBUMS)

    result = {
      new_releases: @new_releases,
      top_rating_albums: @top_rating_albums
    }
    render json: result
  end

  def show
    request_params = SpotifyIdRequestParams.new(params)
    request_params.validate!
    service = ShowAlbumService.new(request_params: request_params, client: @spotify_client)
    service.run!
    render json: service.result.to_json
  end

  def search
    request_params = SearchAlbumsRequestParams.new(params)
    request_params.validate!
    @albums = @spotify_client.search_albums(album_name: request_params.album_name)
    @new_releases = @spotify_client.get_new_releases(limit: Constants::NEW_RELEASE_ALBUMS)
    @top_rating_albums = Album.preload(:artists)
                              .top_ratings(limit: Constants::TOP_RATING_ALBUMS)
    render :index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def set_instance_variables(result)
    @album = result.album
    @top_rating_albums = result.top_rating_albums
    @artists = result.artists
    @songs = result.songs
    @reviews = result.reviews
    @review = Review.new
  end

  def other_than_self(albums:)
    albums.select { |album| album.id != @album.spotify_id }
  end
end

app/views/albums/_album.html.slim
div class=(current_page?(root_path) ? "col-lg-2 col-sm-4 col-xs-6" : "col-lg-3 col-sm-4 col-xs-12 album")
  = link_to album_path(album.id), class: "portfolio-box", ontouchstart: "" do
    = image_tag(album.images.blank? ? Constants::DEFAULT_IMG_URL : album.images.first["url"], class: "img-responsive #{ "img-rounded" unless current_page?(root_path) }", alt: album.name)
    div class="portfolio-box-caption #{'img-rounded' unless current_page?(root_path)}"
      .portfolio-box-caption-content
        .project-category.text-faded.delete-extra-space
          = album.artists.map { |artist| artist.name }.join(' / ')
        .project-name.delete-extra-space
          = album.name

app/views/albums/_persisted_album.html.slim
div class=(current_page?(root_path) ? "col-lg-2 col-sm-4 col-xs-6" : "col-lg-3 col-sm-4 col-xs-12 album")
  = link_to album_path(persisted_album.spotify_id), class: "portfolio-box", ontouchstart: "" do
    = image_tag persisted_album.image, class: "img-responsive #{ "img-rounded" unless current_page?(root_path) }", alt: persisted_album.name
    div class="portfolio-box-caption #{'img-rounded' unless current_page?(root_path)}"
      .portfolio-box-caption-content
        .project-category.text-faded.delete-extra-space
          = persisted_album.artists.map { |artist| artist.name }.join(' / ')
        .project-name.delete-extra-space
          = persisted_album.name

app/views/albums/_search.html.slim
= form_with(url: search_albums_path, method: :get, local: true) do |f|
  .form-group.has-search
    span.fa.fa-search.form-control-button
    = f.text_field :album_name, class: "form-control", placeholder: "Search albums"

app/views/albums/index.html.slim
- provide(:page_title, 'Albums')
.row[style="margin-top:60px;"]
  .col-md-6.col-md-offset-3[style="margin-top:40px;"]
    = render partial: 'search'
hr
.row
  #albums-list
    - if @albums.present?
      .panel.panel-default
        .panel-body.text-center
          h4 Results of #{params[:album_name]}
          = render partial: 'album', collection: @albums
.row
  .panel.panel-default
    .panel-body.text-center
      h4
        | New Releases
      = render partial: 'album', collection: @new_releases
  hr
  .panel.panel-default
    .panel-body.text-center
      h4
        | Top Rating Albums
      = render partial: 'persisted_album', collection: @top_rating_albums

app/views/albums/show.html.slim
- provide(:page_title, @album.name)
.row[style="margin-top:65px;"]
  .col-md-4
    .panel.panel-default
      .panel-body
        = image_tag @album.image, class: "img-responsive img-rounded"
        .album-info
          .star-rating[style="margin-top:10px;" data-score="#{@album.average_rating}"]
        em
          = "#{@album.reviews_count} reviews"
        h3
          == @artists.map { |artist| link_to artist.name, artist_path(artist.id) }.join(' / ')
        h4[style="display:inline;"]
          = @album.name
        span[style="display:inline; float:right;"]
          = @album.release_date
        p[style="margin-top:20px;"]
          = link_to icon('fab', 'spotify', 'Go to Spotify'), @album.external_urls, class: 'btn btn-success btn-block', target: '_blank'
  .col-md-8[style="margin-bottom:20px;"]
    .panel.panel-default
      .panel-body
        h4
          | Tracks
        = render partial: 'songs/song_list', collection: @songs, as: :song, cached: true
    .panel.panel-default
      .panel-body
        h4
          | Reviews
        a href="#" data-toggle="modal" data-target="#{current_user ? '#createReviewModal' : '#promoteSignInModal'}"
          | Review this album
        = render partial: 'reviews/review', collection: @reviews
        = paginate @reviews
    / コンポーネント化
    .modal.fade id="createReviewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
      .modal-dialog[role="document"]
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
            h4#myModalLabel.modal-title
              | Add review
          span#error-messages-for-update
          .modal-body
            = render 'reviews/form', review: @review, album: @album, id: @album.id, type: 'new'
    .modal.fade id="promoteSignInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
      .modal-dialog[role="document"]
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
            h4#myModalLabel.modal-title
              | Do you want to review this album?
          .modal-body
            = render 'users/promote_signin'
hr
- @artists.each do |artist|
  .row
    .panel.panel-default
      .panel-body.text-center
        h4 More by #{artist.name}
        = render partial: 'albums/album', collection: other_than_self(albums: artist.albums)
hr
.row
  .panel.panel-default
    .panel-body.text-center
      h4
        | Top Rating Albums
      = render partial: 'albums/persisted_album', collection: @top_rating_albums