config/routes.rb
Rails.application.routes.draw do
  root 'creatives#index'
  get 'creatives/terms_and_conditions', as: :terms
  get 'creatives/privacy_notice', as: :privacy

  devise_for :users,
              controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                             passwords: 'users/passwords',
                             registrations: 'users/registrations',
                             sessions: 'users/sessions' }
  resources :users, only: %i[show edit update]
  resources :artists, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :albums, only: %i[index show destroy] do
    get :search, on: :collection
  end
  resources :reviews, only: %i[create update destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  include ApiClientGeneratable

  before_action :generate_spotify_client, only: %i[index]

  def index
    @top_rating_albums = Album.preload(:artists)
                              .top_ratings(limit: Constants::ALBUMS_FOR_TOP_PAGE)
    @new_releases = @spotify_client.get_new_releases(limit: Constants::ALBUMS_FOR_TOP_PAGE)
  end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/creatives/_bg_primary.html.slim
section#about.bg-primary
  .container
    .row
      .col-lg-8.col-lg-offset-2.text-center
        h2.section-heading
          | We've got what you need!
        hr.light
        = link_to "Get Started!", user_signed_in? ? albums_path : new_user_session_path, class: 'btn btn-default btn-xl'

app/views/creatives/_call_to_action.html.slim
aside.bg-dark
  .container.text-center
    .call-to-action
      h2
        | Free Download at App Store & Google Play!
      a.btn.btn-default.btn-xl.wow.tada[href="#"]
        | Available Soon...

app/views/creatives/_contact.html.slim
section#contact
  .container
    .row
      .col-lg-8.col-lg-offset-2.text-center
        h2.section-heading
          | Let's Get In Touch!
        hr.primary
        p
          | Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!
      .col-lg-4.col-lg-offset-2.text-center
        i.fas.fa-phone.fa-3x.wow.bounceIn
        p
          | 123-456-6789
      .col-lg-4.text-center
        i.far.fa-envelope.fa-3x.wow.bounceIn[data-wow-delay=".1s"]
        p
          a[href="mailto:info@musicritic.net"]
            | info@musicritic.net

app/views/creatives/_footer.html.slim
footer
  .footer-top
    span
      = link_to 'Home', root_path, data: { turbolinks: 'false' }
    span
      = link_to 'About', '/#services', data: { turbolinks: 'false' }
    span
      = link_to 'Contact', '/#contact', data: { turbolinks: 'false' }
    span
      = link_to 'Terms', terms_path
    span[style="margin-right:-10px;"]
      = link_to 'Privacy', privacy_path
  .footer-middle
    span.fab.fa-facebook
    span.fab.fa-twitter
    span.fab.fa-github[style="margin-right:-10px;"]
  .footer-bottom
    span
      | ©
      = "#{Time.zone.now.year} "
      = "#{Constants::APP_NAME} "
      | - All Rights Reserved

app/views/creatives/_header.html.slim
header
  .header-content
    .header-content-inner
      h1
        | Your Favorite Music with Your Review
      hr
      p
        | We can help you find new sophisticated, mellow, traquil or emotional music.
      = link_to "Find Out More", user_signed_in? ? albums_path : new_user_session_path, class: "btn btn-primary btn-xl page-scroll"

app/views/creatives/_navbar.html.slim
nav#mainNav.navbar.navbar-default.navbar-fixed-top[style="background-color:black;"]
  .container
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand.page-scroll[href="/" data-turbolinks="false"]
        i.fas.fa-headphones-alt[style="margin-right:5px;"]
        = Constants::APP_NAME
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Artists", artists_path
        li
          = link_to "Albums", albums_path
        - if user_signed_in?
          li
            = link_to "Account", user_path(current_user)
          li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          li
            = link_to "Login", new_user_session_path
          li
            = link_to "Register", new_user_registration_path

app/views/creatives/_new_releases.html.slim
section#new-releases.no-padding
  .container-fluid.no-padding
    .row
      .col-lg-12.text-center[style="padding-top:30px; padding-bottom:10px;"]
        h2.section-heading
          | New Releases
        hr.primary
    .row.no-gutter
      = render partial: 'albums/album', collection: albums

app/views/creatives/_services.html.slim
section#services
  .container
    .row
      .col-lg-12.text-center
        h2.section-heading
          | Our Services
        hr.primary
  .container
    .row
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-music.wow.bounceIn.text-primary
          h3
            | Listen Songs
          p.text-muted
            | You can listen new curious songs.
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-paper-plane.wow.bounceIn.text-primary[data-wow-delay=".1s"]
          h3
            | Post Your Review
          p.text-muted
            | You can review with 5-grade star.
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-newspaper.wow.bounceIn.text-primary[data-wow-delay=".2s"]
          h3
            | Watch Other's Review
          p.text-muted
            | You can watch other's review and find some interesting music !
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-heart.wow.bounceIn.text-primary[data-wow-delay=".3s"]
          h3
            | Find New Favorite Song
          p.text-muted
            | You can find new favorite song !

app/views/creatives/_top_rating_albums.html.slim
section#top-rating-albums.no-padding
  .container-fluid.no-padding
    .row
      .col-lg-12.text-center[style="padding-top:30px; padding-bottom:10px;"]
        h2.section-heading
          | Top Rating Albums
        hr.primary
    .row.no-gutter
      = render partial: 'albums/persisted_album', collection: albums

app/views/creatives/index.html.slim
= render 'header'
= render partial: 'top_rating_albums', locals: { albums: @top_rating_albums }
= render partial: 'new_releases', locals: { albums: @new_releases }
= render 'services'
= render 'call_to_action'
= render 'contact'

app/views/creatives/privacy_notice.html.slim
.container[style="margin-top:60px;"]
  .row
    .col-md-12
      h2
        | Privacy Policy for MusiCritic
      p
        | At MusiCritic, accessible from https://musicritic.net, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by MusiCritic and how we use it.
      p
        | If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us through email at info@musicritic.net
      h2
        | General Data Protection Regulation (GDPR)
      p
        | We are a Data Controller of your information.
      p
        | MusiCritic legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Information we collect and the specific context in which we collect the information:
      ul
        li
          | MusiCritic needs to perform a contract with you
        li
          | You have given MusiCritic permission to do so
        li
          | Processing your personal information is in MusiCritic legitimate interests
        li
          | MusiCritic needs to comply with the law
      p
        | MusiCritic will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies. Our Privacy Policy was generated with the help of
        a[href="https://www.gdprprivacynotice.com/"]
          | GDPR Privacy Policy Generator
        | .
      p
        | If you are a resident of the European Economic Area (EEA), you have certain data protection rights. If you wish to be informed what Personal Information we hold about you and if you want it to be removed from our systems, please contact us.
      p
        | In certain circumstances, you have the following data protection rights:
      ul
        li
          | The right to access, update or to delete the information we have on you.
        li
          | The right of rectification.
        li
          | The right to object.
        li
          | The right of restriction.
        li
          | The right to data portability
        li
          | The right to withdraw consent
      h2
        | Log Files
      p
        | MusiCritic follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.
      h2
        | Privacy Policies
      p
        | You may consult this list to find the Privacy Policy for each of the advertising partners of MusiCritic.
      p
        | Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on MusiCritic, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.
      p
        | Note that MusiCritic has no access to or control over these cookies that are used by third-party advertisers.
      h2
        | Third Party Privacy Policies
      p
        | MusiCritic's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You may find a complete list of these Privacy Policies and their links here: Privacy Policy Links.
      p
        | You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. What Are Cookies?
      h2
        | Children's Information
      p
        | Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.
      p
        | MusiCritic does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.
      h2
        | Online Privacy Policy Only
      p
        | Our Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in MusiCritic. This policy is not applicable to any information collected offline or via channels other than this website.
      h2
        | Consent
      p
        | By using our website, you hereby consent to our Privacy Policy and agree to its terms.

app/views/creatives/terms_and_conditions.html.slim
.container[style="margin-top:60px;"]
  .row
    .col-md-12
      h2
        | Welcome to MusiCritic
      p
        | These terms and conditions outline the rules and regulations for the use of MusiCritic's Website.
      br
      p
        | By accessing this website we assume you accept these terms and conditions in full. Do not continue to use MusiCritic's website if you do not accept all of the terms and conditions stated on this page.
      p
        | The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and any or all Agreements: "Client", "You" and "Your" refers to you, the person accessing this website and accepting the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves, or either the Client or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner, whether by formal meetings of a fixed duration, or any other means, for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services/products, in accordance with and subject to, prevailing law of . Any use of the above terminology or other words in the singular, plural, capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same.
      h2
        | License
      p
        | Unless otherwise stated, MusiCritic and/or it's licensors own the intellectual property rights for all material on MusiCritic. All intellectual property rights are reserved. You may view and/or print pages from https://musicritic.net for your own personal use subject to restrictions set in these terms and conditions.
      p
        | You must not:
      ol
        li
          | Republish material from https://musicritic.net
        li
          | Sell, rent or sub-license material from https://musicritic.net
        li
          | Reproduce, duplicate or copy material from https://musicritic.net
      p
        | Redistribute content from MusiCritic (unless content is specifically made for redistribution).
      h2
        | User Comments
      ol
        li
          | This Agreement shall begin on the date hereof.
        li
          | Certain parts of this website offer the opportunity for users to post and exchange opinions, information, material and data ('Comments') in areas of the website. MusiCritic does not screen, edit, publish or review Comments prior to their appearance on the website and Comments do not reflect the views or opinions of MusiCritic, its agents or affiliates. Comments reflect the view and opinion of the person who posts such view or opinion. To the extent permitted by applicable laws MusiCritic shall not be responsible or liable for the Comments or for any loss cost, liability, damages or expenses caused and or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.
        li
          | MusiCritic reserves the right to monitor all Comments and to remove any Comments which it considers in its absolute discretion to be inappropriate, offensive or otherwise in breach of these Terms and Conditions.
        li
          | You warrant and represent that:
          ol
            li
              | You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;
            li
              | The Comments do not infringe any intellectual property right, including without limitation copyright, patent or trademark, or other proprietary right of any third party;
            li
              | The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material or material which is an invasion of privacy
            li
              | The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.
        li
          | You hereby grant to
          strong
            | MusiCritic
          |  a non-exclusive royalty-free license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.
      h2
        | Hyperlinking to our Content
      ol
        li
          | The following organizations may link to our Web site without prior written approval:
          ol
            li
              | Government agencies;
            li
              | Search engines;
            li
              | News organizations;
            li
              | Online directory distributors when they list us in the directory may link to our Web site in the same manner as they hyperlink to the Web sites of other listed businesses; and
            li
              | Systemwide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.
      ol[start="2"]
        li
          | These organizations may link to our home page, to publications or to other Web site information so long as the link: (a) is not in any way misleading; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party's site.
        li
          | We may consider and approve in our sole discretion other link requests from the following types of organizations:
          ol
            li
              | commonly-known consumer and/or business information sources such as Chambers of Commerce, American Automobile Association, AARP and Consumers Union;
            li
              | dot.com community sites;
            li
              | associations or other groups representing charities, including charity giving sites,
            li
              | online directory distributors;
            li
              | internet portals;
            li
              | accounting, law and consulting firms whose primary clients are businesses; and
            li
              | educational institutions and trade associations.
      p
        | We will approve link requests from these organizations if we determine that: (a) the link would not reflect unfavorably on us or our accredited businesses (for example, trade associations or other organizations representing inherently suspect types of business, such as work-at-home opportunities, shall not be allowed to link); (b)the organization does not have an unsatisfactory record with us; (c) the benefit to us from the visibility associated with the hyperlink outweighs the absence of <?=$companyName?>; and (d) where the link is in the context of general resource information or is otherwise consistent with editorial content in a newsletter or similar product furthering the mission of the organization.
      p
        | These organizations may link to our home page, to publications or to other Web site information so long as the link: (a) is not in any way misleading; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and it products or services; and (c) fits within the context of the linking party's site.
      p
        | If you are among the organizations listed in paragraph 2 above and are interested in linking to our website, you must notify us by sending an e-mail to
        a[href="mailto:info@musicritic.net" title="send an email to info@musicritic.net"]
          | info@musicritic.net
        | . Please include your name, your organization name, contact information (such as a phone number and/or e-mail address) as well as the URL of your site, a list of any URLs from which you intend to link to our Web site, and a list of the URL(s) on our site to which you would like to link. Allow 2-3 weeks for a response.
      p
        | Approved organizations may hyperlink to our Web site as follows:
      ol
        li
          | By use of our corporate name; or
        li
          | By use of the uniform resource locator (Web address) being linked to; or
        li
          | By use of any other description of our Web site or material being linked to that makes sense within the context and format of content on the linking party's site.
      p
        | No use of MusiCritic's logo or other artwork will be allowed for linking absent a trademark license agreement.
      h2
        | Iframes
      p
        | Without prior approval and express written permission, you may not create frames around our Web pages or use other techniques that alter in any way the visual presentation or appearance of our Web site.
      h2
        | Reservation of Rights
      p
        | We reserve the right at any time and in its sole discretion to request that you remove all links or any particular link to our Web site. You agree to immediately remove all links to our Web site upon such request. We also reserve the right to amend these terms and conditions and its linking policy at any time. By continuing to link to our Web site, you agree to be bound to and abide by these linking terms and conditions.
      h2
        | Removal of links from our website
      p
        | If you find any link on our Web site or any linked web site objectionable for any reason, you may contact us about this. We will consider requests to remove links but will have no obligation to do so or to respond directly to you.
      p
        | Whilst we endeavour to ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we commit to ensuring that the website remains available or that the material on the website is kept up to date.
      h2
        | Content Liability
      p
        | We shall have no responsibility or liability for any content appearing on your Web site. You agree to indemnify and defend us against all claims arising out of or based upon your Website. No link(s) may appear on any page on your Web site or within any context containing content or materials that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.
      h2
        | Disclaimer
      p
        | To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill). Nothing in this disclaimer will:
      ol
        li
          | limit or exclude our or your liability for death or personal injury resulting from negligence;
        li
          | limit or exclude our or your liability for fraud or fraudulent misrepresentation;
        li
          | limit any of our or your liabilities in any way that is not permitted under applicable law; or
        li
          | exclude any of our or your liabilities that may not be excluded under applicable law.
      p
        | The limitations and exclusions of liability set out in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer or in relation to the subject matter of this disclaimer, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty.
      p
        | To the extent that the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.
      h2
      p
      h2
        | Credit & Contact Information
      p
        | This Terms and conditions page was created at
        a[style="color:inherit;text-decoration:none;cursor:text;" href="https://termsandconditionstemplate.com"]
          | termsandconditionstemplate.com
        |  generator. If you have any queries regarding any of our terms, please contact us.